# Generated by Django 4.2 on 2024-10-10 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_author_alter_post_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 21, 57, 6, 401789, tzinfo=datetime.timezone.utc)),
        ),
    ]
